version: '3.7'

services:
  communicator:
    build: ./stream_communication
    command: python stream_communication.py
    networks:
      - wiki-network
    depends_on:
      cassandra-load-keyspace:
        condition: service_completed_successfully

  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    expose:
      - "9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - wiki-network

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:3.11.2
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra/schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    networks:
      - wiki-network

  web-app:
    build: .
    command: python ./webapp/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    expose:
      - "5000"
    depends_on:
      - communicator
    networks:
      - wiki-network
    healthcheck:
      test: curl --fail http://0.0.0.0:5000/ || exit 1
      interval: 60s
      retries: 5
      timeout: 10s

  spark:
    build: .
    command: python3 api_1/spark_processing.py
    networks:
      - wiki-network
    depends_on:
      - web-app

networks:
  wiki-network:
    name: wiki-network