version: '3.7'

services:
  communicator:
    build: ./stream_communication
    command: python stream_communication.py
    networks:
      - wiki-network
    depends_on:
      cassandra-load-keyspace:
        condition: service_completed_successfully

  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    expose:
      - "9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - wiki-network

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:3.11.2
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra/schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    networks:
      - wiki-network

  web-app:
    build: .
    command: python ./webapp/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    expose:
      - "5000"
    depends_on:
      - communicator
    networks:
      - wiki-network
    healthcheck:
      test: curl --fail http://0.0.0.0:5000/ || exit 1
      interval: 60s
      retries: 5
      timeout: 10s

  #  spark:
  #    image: docker.io/bitnami/spark:3
  #    networks:
  #      - wiki-network
  #    environment:
  #      - SPARK_MODE=master
  #      - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #      - SPARK_RPC_ENCRYPTION_ENABLED=no
  #      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #      - SPARK_SSL_ENABLED=no
  #    ports:
  #      - '8080:8080'
  #  spark-worker:
  #    image: docker.io/bitnami/spark:3
  #    networks:
  #      - wiki-network
  #    environment:
  #      - SPARK_MODE=worker
  #      - SPARK_MASTER_URL=spark://spark:7077
  #      - SPARK_WORKER_MEMORY=1G
  #      - SPARK_WORKER_CORES=1
  #      - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #      - SPARK_RPC_ENCRYPTION_ENABLED=no
  #      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #      - SPARK_SSL_ENABLED=no


networks:
  wiki-network:
    name: wiki-network