version: '2'

services:
  cassandra-node1:
    image: library/cassandra:latest
    networks:
      - wiki-network
    environment:
      - CASSANDRA_SEEDS=cassandra-node1, cassandra-node2, cassandra-node3
  cassandra-node2:
    extends:
      service: cassandra-node1
  cassandra-node3:
    extends:
      service: cassandra-node1

  spark:
    image: docker.io/bitnami/spark:3
    networks:
      - wiki-network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3
    networks:
      - wiki-network
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no


networks:
  wiki-network:
    name: wiki-network