FROM datamechanics/spark:3.1-latest

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

# RUN pip install --upgrade pip

RUN pip install cassandra-driver

RUN pip install pyspark

RUN pip install apscheduler

WORKDIR /api_1

COPY spark_processing.py /opt/app/

CMD ["python3", "/opt/app/spark_processing.py"]